"use client";
/* eslint-disable react-hooks/refs, react-hooks/immutability */

import { createPortal } from "react-dom";
import { forwardRef, useEffect, useImperativeHandle, useRef, useState, type ChangeEvent, type KeyboardEvent, type ReactNode } from "react";
import type { MediaPlayerControls, MediaPlayerError, MediaPlayerProps, MediaPlayerRef, MediaPlayerState, MediaSource } from "@/types/media-player";

const defaultRates = [0.25, 0.5, 0.75, 1, 1.25, 1.5, 1.75, 2];
const sourceValue = (source: MediaSource) => typeof source === "string" ? source : source.src;
const formatTime = (value: number) => !Number.isFinite(value) ? "0:00" : `${Math.floor(value / 60)}:${Math.floor(value % 60).toString().padStart(2, "0")}`;
const isEditable = (target: EventTarget | null) => target instanceof HTMLElement && (target.isContentEditable || ["INPUT", "TEXTAREA", "SELECT"].includes(target.tagName));

type IconName = "play" | "pause" | "volume-low" | "volume-medium" | "volume-high" | "mute" | "settings" | "fullscreen" | "compress" | "pip" | "captions" | "back" | "chevron" | "close" | "skip-back" | "skip-forward" | "more" | "music";
const Icon = ({ name, size = 20 }: { name: IconName; size?: number }) => {
  const paths: Record<IconName, ReactNode> = {
    play: <path d="m8 5 11 7-11 7V5Z" />, pause: <><path d="M7 5h3v14H7z" /><path d="M14 5h3v14h-3z" /></>,
    "volume-low": <><path d="M4 10v4h3l4 3V7l-4 3H4Z" /><path d="M15 10a3 3 0 0 1 0 4" /></>, "volume-medium": <><path d="M4 10v4h3l4 3V7l-4 3H4Z" /><path d="M15 9a4 4 0 0 1 0 6m3-8a8 8 0 0 1 0 10" /></>, "volume-high": <><path d="M4 10v4h3l4 3V7l-4 3H4Z" /><path d="M15 9a4 4 0 0 1 0 6m3-8a8 8 0 0 1 0 10" /></>, mute: <><path d="M4 10v4h3l4 3V7l-4 3H4Z" /><path d="m16 10 4 4m0-4-4 4" /></>,
    settings: <><path d="M12 8.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7Z" /><path d="m19 13 .1-1-.1-1 2-1.5-2-3.5-2.3 1a8 8 0 0 0-1.7-1L15 3H9l.2 3a8 8 0 0 0-1.7 1l-2.3-1-2 3.5L5.2 11a8 8 0 0 0 0 2l-2 1.5 2 3.5 2.3-1a8 8 0 0 0 1.7 1L9 21h6l-.2-3a8 8 0 0 0 1.7-1l2.3 1 2-3.5L19 13Z" /></>,
    fullscreen: <><path d="M8 3H3v5m13-5h5v5M8 21H3v-5m18 0v5h-5" /></>, compress: <><path d="M9 3v6H3m12-6v6h6M9 21v-6H3m12 6v-6h6" /></>,
    pip: <><path d="M3 5h18v14H3z" /><path d="M12 13h7v4h-7z" /></>, captions: <><path d="M3 5h18v14H3z" /><path d="M6 12h5m2 0h5M6 15h3m2 0h4" /></>,
    back: <path d="m15 18-6-6 6-6" />, chevron: <path d="m9 6 6 6-6 6" />, close: <path d="m6 6 12 12m0-12L6 18" />, "skip-back": <><path d="M5 5v14" /><path d="m18 6-8 6 8 6V6Z" /><path d="m11 6-8 6 8 6" /></>, "skip-forward": <><path d="M19 5v14" /><path d="m6 6 8 6-8 6V6Z" /><path d="m13 6 8 6-8 6" /></>,
    more: <><circle cx="5" cy="12" r="1" /><circle cx="12" cy="12" r="1" /><circle cx="19" cy="12" r="1" /></>, music: <><path d="M9 18V5l10-2v13" /><circle cx="6" cy="18" r="3" /><circle cx="16" cy="16" r="3" /></>,
  };
  return <svg aria-hidden="true" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{paths[name]}</svg>;
};

export const MediaPlayer = forwardRef<MediaPlayerRef, MediaPlayerProps>(function MediaPlayer({
  type, src, poster, artwork, preload = "metadata", autoplay = false, muted = false, loop = false, controls = true, captions = [], chapters, quality = [], playbackRate = true, playbackRates = defaultRates, seekStep = 10, keyboardShortcuts = true, mediaSession, className = "", accent = "#c8f169", onPlay, onPause, onEnded, onTimeUpdate, onProgress, onLoadedMetadata, onWaiting, onPlaying, onVolumeChange, onRateChange, onFullscreenChange, onError, onQualityChange, onCaptionChange, onSeek,
}, ref) {
  const mediaRef = useRef<HTMLMediaElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const settingsButtonRef = useRef<HTMLButtonElement>(null);
  const [state, setState] = useState<MediaPlayerState>({ playing: false, currentTime: 0, duration: 0, volume: 1, muted, buffered: 0, buffering: false, fullscreen: false, pictureInPicture: false, playbackRate: 1, quality: quality[0]?.label, captionsEnabled: false, controlsVisible: true });
  const [menu, setMenu] = useState<"main" | "speed" | "quality" | null>(null);
  const [volumeOpen, setVolumeOpen] = useState(false);
  const [seekFeedback, setSeekFeedback] = useState<"back" | "forward" | null>(null);
  const [notice, setNotice] = useState("");
  const [settingsPosition, setSettingsPosition] = useState({ top: 12, left: 12 });
  const [volumePosition, setVolumePosition] = useState({ top: 12, left: 12 });
  const showControls = state.controlsVisible;
  const config: Required<MediaPlayerControls> = { play: true, volume: true, progress: true, captions: captions.length > 0, settings: playbackRate || quality.length > 1, fullscreen: type === "video", pictureInPicture: type === "video", ...(typeof controls === "object" ? controls : {}) };
  const hasControls = controls !== false;
  const positionSettings = () => { const button = settingsButtonRef.current; if (!button) return; const rect = button.getBoundingClientRect(); const width = Math.min(280, window.innerWidth - 24); const below = rect.bottom + 8; const top = below + 360 <= window.innerHeight - 12 ? below : Math.max(12, rect.top - 368); const left = Math.min(Math.max(12, rect.right - width), window.innerWidth - width - 12); setSettingsPosition({ top, left }); };
  const positionVolume = () => { const player = containerRef.current; if (!player) return; const rect = player.getBoundingClientRect(); setVolumePosition({ top: Math.max(12, rect.top + 12), left: rect.left + rect.width / 2 }); };
  const setError = (error: MediaPlayerError) => { setState((current) => ({ ...current, error, buffering: false, playing: false })); onError?.(error); };
  const play = async () => { try { await mediaRef.current?.play(); } catch (error) { setError({ message: error instanceof Error ? error.message : "Playback was blocked by the browser." }); } };
  const pause = () => mediaRef.current?.pause();
  const togglePlay = () => mediaRef.current?.paused ? play() : (pause(), Promise.resolve());
  const seek = (time: number) => { if (!mediaRef.current) return; const next = Math.max(0, Math.min(time, mediaRef.current.duration || time)); mediaRef.current.currentTime = next; onSeek?.(next); };
  const setVolume = (volume: number) => { if (!mediaRef.current) return; mediaRef.current.volume = volume; mediaRef.current.muted = volume === 0; };
  const toggleMute = () => { if (mediaRef.current) mediaRef.current.muted = !mediaRef.current.muted; };
  const setPlaybackRate = (rate: number) => { if (mediaRef.current) mediaRef.current.playbackRate = rate; };
  const requestFullscreen = async () => { if (!containerRef.current?.requestFullscreen) { setNotice("Fullscreen is not supported in this browser."); return; } try { await containerRef.current.requestFullscreen(); const orientation = screen.orientation as ScreenOrientation & { lock?: (orientation: string) => Promise<void> }; if (orientation.lock) await orientation.lock("landscape").catch(() => undefined); } catch { setNotice("Fullscreen could not be started in this browser."); } };
  const exitFullscreen = async () => { try { if (document.fullscreenElement) await document.exitFullscreen(); } catch { setNotice("Fullscreen could not be closed."); } finally { if (screen.orientation?.unlock) screen.orientation.unlock(); } };
  const enterPictureInPicture = async () => { const video = mediaRef.current as HTMLVideoElement | null; if (!video || !("requestPictureInPicture" in video)) { setNotice("Picture-in-Picture is not supported in this browser."); return; } try { await video.requestPictureInPicture(); } catch { setNotice("Picture-in-Picture is not available right now."); } };
  const exitPictureInPicture = async () => { if (document.pictureInPictureElement) await document.exitPictureInPicture(); };
  useImperativeHandle(ref, () => ({ play, pause, togglePlay, seek, setVolume, toggleMute, setPlaybackRate, requestFullscreen, exitFullscreen, enterPictureInPicture, exitPictureInPicture, getState: () => state }));
  useEffect(() => { if (mediaRef.current) { mediaRef.current.volume = state.volume; mediaRef.current.muted = state.muted; } }, [state.muted, state.volume]);
  useEffect(() => { const onFullscreen = () => { const fullscreen = Boolean(document.fullscreenElement); setState((current) => ({ ...current, fullscreen })); if (!fullscreen && screen.orientation?.unlock) screen.orientation.unlock(); onFullscreenChange?.(fullscreen); }; document.addEventListener("fullscreenchange", onFullscreen); return () => document.removeEventListener("fullscreenchange", onFullscreen); }, [onFullscreenChange]);
  useEffect(() => { if (!mediaSession || !("mediaSession" in navigator)) return; navigator.mediaSession.metadata = new MediaMetadata(mediaSession); (["play", "pause", "seekbackward", "seekforward"] as MediaSessionAction[]).forEach((action) => { try { navigator.mediaSession.setActionHandler(action, action === "play" ? play : action === "pause" ? pause : () => seek((mediaRef.current?.currentTime ?? 0) + (action === "seekforward" ? seekStep : -seekStep))); } catch { /* unsupported action */ } }); return () => (["play", "pause", "seekbackward", "seekforward"] as MediaSessionAction[]).forEach((action) => { try { navigator.mediaSession.setActionHandler(action, null); } catch { /* unsupported action */ } }); }, [mediaSession, seekStep]);
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(""), 2600); return () => window.clearTimeout(timer); }, [notice]);
  useEffect(() => { if (!menu) return; positionSettings(); const onResize = () => positionSettings(); const onPointerDown = (event: PointerEvent) => { const target = event.target as Node; if (!(target instanceof Element && target.closest(".external-media-menu")) && target !== settingsButtonRef.current && !settingsButtonRef.current?.contains(target)) setMenu(null); }; const onDocumentKeyDown = (event: globalThis.KeyboardEvent) => { if (event.key === "Escape") setMenu(null); }; window.addEventListener("resize", onResize); window.addEventListener("scroll", onResize, true); document.addEventListener("pointerdown", onPointerDown); document.addEventListener("keydown", onDocumentKeyDown); return () => { window.removeEventListener("resize", onResize); window.removeEventListener("scroll", onResize, true); document.removeEventListener("pointerdown", onPointerDown); document.removeEventListener("keydown", onDocumentKeyDown); }; }, [menu]);
  const toggleCaptions = () => { const tracks = mediaRef.current?.textTracks; if (!tracks) return; const enabled = !state.captionsEnabled; for (let index = 0; index < tracks.length; index += 1) tracks[index].mode = enabled ? "showing" : "hidden"; setState((current) => ({ ...current, captionsEnabled: enabled })); onCaptionChange?.(enabled); };
  const onKeyDown = (event: KeyboardEvent<HTMLDivElement>) => { if (event.key === "Escape") { setMenu(null); setVolumeOpen(false); return; } if (!keyboardShortcuts || isEditable(event.target)) return; if (event.key === " " || event.key.toLowerCase() === "k") { event.preventDefault(); void togglePlay(); } if (event.key === "ArrowLeft") seek((mediaRef.current?.currentTime ?? 0) - seekStep); if (event.key === "ArrowRight") seek((mediaRef.current?.currentTime ?? 0) + seekStep); if (event.key === "ArrowUp") setVolume(Math.min(1, (mediaRef.current?.volume ?? 1) + 0.05)); if (event.key === "ArrowDown") setVolume(Math.max(0, (mediaRef.current?.volume ?? 1) - 0.05)); if (event.key.toLowerCase() === "m") toggleMute(); if (event.key.toLowerCase() === "f" && type === "video") void requestFullscreen(); if (event.key.toLowerCase() === "p" && type === "video") void enterPictureInPicture(); if (event.key.toLowerCase() === "c" && captions.length) toggleCaptions(); if (event.key === ">") setPlaybackRate(Math.min(2, (mediaRef.current?.playbackRate ?? 1) + 0.25)); if (event.key === "<") setPlaybackRate(Math.max(0.25, (mediaRef.current?.playbackRate ?? 1) - 0.25)); };
  const switchQuality = (label: string) => { const selected = quality.find((item) => item.label === label); const media = mediaRef.current; if (!selected || !media) return; const time = media.currentTime; const wasPlaying = !media.paused; media.src = sourceValue(selected.src); media.load(); media.addEventListener("loadedmetadata", () => { media.currentTime = time; if (wasPlaying) void media.play(); }, { once: true }); setState((current) => ({ ...current, quality: label })); onQualityChange?.(label); setMenu(null); };
  const showSeekFeedback = (direction: "back" | "forward") => { seek((mediaRef.current?.currentTime ?? 0) + (direction === "forward" ? seekStep : -seekStep)); setSeekFeedback(direction); window.setTimeout(() => setSeekFeedback(null), 500); };
  const mediaProps = { src: sourceValue(src), preload, autoPlay: autoplay, muted, loop, poster: type === "video" ? poster : undefined, className: "media-element", onClick: () => { if (type === "video") setState((current) => ({ ...current, controlsVisible: !current.controlsVisible })); }, onPlay: () => { setState((current) => ({ ...current, playing: true, buffering: false })); onPlay?.(); }, onPause: () => { setState((current) => ({ ...current, playing: false })); onPause?.(); }, onEnded: () => { setState((current) => ({ ...current, playing: false })); onEnded?.(); }, onTimeUpdate: () => { const currentTime = mediaRef.current?.currentTime ?? 0; setState((current) => ({ ...current, currentTime })); onTimeUpdate?.(currentTime); }, onProgress: () => { const media = mediaRef.current; const buffered = media?.duration && media.buffered.length ? media.buffered.end(media.buffered.length - 1) / media.duration : 0; setState((current) => ({ ...current, buffered })); onProgress?.(buffered); }, onLoadedMetadata: () => { const duration = mediaRef.current?.duration ?? 0; setState((current) => ({ ...current, duration, error: undefined })); onLoadedMetadata?.(duration); }, onWaiting: () => { setState((current) => ({ ...current, buffering: true })); onWaiting?.(); }, onPlaying: () => { setState((current) => ({ ...current, buffering: false })); onPlaying?.(); }, onRateChange: () => { const rate = mediaRef.current?.playbackRate ?? 1; setState((current) => ({ ...current, playbackRate: rate })); onRateChange?.(rate); }, onVolumeChange: () => { const media = mediaRef.current; if (!media) return; setState((current) => ({ ...current, volume: media.volume, muted: media.muted })); onVolumeChange?.(media.volume, media.muted); }, onError: () => { const error = mediaRef.current?.error; setError({ code: error?.code, nativeError: error, message: "The media could not be loaded. Check the source and browser format support." }); } };
  const controlButton = (label: string, icon: IconName, onClick: () => void, active = false, extra = "") => <button type="button" className={`control-button ${active ? "active" : ""} ${extra}`} onClick={onClick} aria-label={label} title={label}><Icon name={icon} /></button>;
  const progress = <div className="progress-wrap"><div className="buffered-bar" style={{ width: `${state.buffered * 100}%` }} /><input aria-label="Seek through media" type="range" min="0" max={state.duration || 0} step="0.1" value={Math.min(state.currentTime, state.duration || 0)} onChange={(event: ChangeEvent<HTMLInputElement>) => seek(Number(event.target.value))} /></div>;
  const volumeIcon = state.muted || state.volume === 0 ? "mute" : state.volume < 0.34 ? "volume-low" : state.volume < 0.7 ? "volume-medium" : "volume-high";
  const volumeControl = config.volume && <div className="volume-control">{controlButton("Open volume controls", volumeIcon, () => { positionVolume(); setVolumeOpen((open) => !open); }, volumeOpen)}<div className={`volume-popover ${volumeOpen ? "open" : ""}`} style={{ top: volumePosition.top, left: volumePosition.left }}><input aria-label="Volume" type="range" min="0" max="1" step="0.05" value={state.muted ? 0 : state.volume} onChange={(event) => setVolume(Number(event.target.value))} /></div><input aria-label="Volume" className="volume-range" type="range" min="0" max="1" step="0.05" value={state.muted ? 0 : state.volume} onChange={(event) => setVolume(Number(event.target.value))} /></div>;
  const settings = config.settings && <div className="menu-wrap"><button ref={settingsButtonRef} type="button" className={`control-button ${menu ? "active" : ""}`} onClick={() => { if (menu) setMenu(null); else { positionSettings(); setMenu("main"); } }} aria-label="Settings" aria-expanded={Boolean(menu)} title="Settings"><Icon name="settings" /></button></div>;
  const settingsPanel = menu && typeof document !== "undefined" ? createPortal(<div className="external-media-menu media-menu" style={{ top: settingsPosition.top, left: settingsPosition.left }} role="menu">{menu === "main" && <><strong>Player settings</strong>{playbackRate && <button type="button" role="menuitem" onClick={() => setMenu("speed")}>Playback speed <span>{state.playbackRate}x <Icon name="chevron" size={16} /></span></button>}{quality.length > 1 && <button type="button" role="menuitem" onClick={() => setMenu("quality")}>Video quality <span>{state.quality ?? "Auto"} <Icon name="chevron" size={16} /></span></button>}</>}{menu === "speed" && <><button type="button" className="menu-back" role="menuitem" onClick={() => setMenu("main")}><Icon name="back" size={16} /> Playback speed</button>{playbackRates.map((rate) => <button type="button" role="menuitem" key={rate} className={state.playbackRate === rate ? "selected" : ""} onClick={() => { setPlaybackRate(rate); setMenu(null); }}>{rate}x{state.playbackRate === rate && <span>Selected</span>}</button>)}</>}{menu === "quality" && <><button type="button" className="menu-back" role="menuitem" onClick={() => setMenu("main")}><Icon name="back" size={16} /> Video quality</button>{quality.map((item) => <button type="button" role="menuitem" key={item.label} className={state.quality === item.label ? "selected" : ""} onClick={() => switchQuality(item.label)}>{item.label}{state.quality === item.label && <span>Selected</span>}</button>)}</>}</div>, document.body) : null;
  const utilityControls = hasControls && <div className="player-utility">{config.captions && controlButton("Toggle captions", "captions", toggleCaptions, state.captionsEnabled, "captions-control")}{settings}</div>;
  const controlsMarkup = hasControls && <div className={`media-controls ${showControls ? "visible" : "hidden"}`}>{progress}<div className="control-row">{controlButton("Skip backward 10 seconds", "skip-back", () => showSeekFeedback("back"))}{config.play && controlButton(state.playing ? "Pause" : "Play", state.playing ? "pause" : "play", () => void togglePlay(), false, "play-button")}{controlButton("Skip forward 10 seconds", "skip-forward", () => showSeekFeedback("forward"))}<span className="time-label">{formatTime(state.currentTime)} / {formatTime(state.duration)}</span><span className="control-spacer" />{volumeControl}{config.pictureInPicture && controlButton("Picture-in-Picture", "pip", () => void enterPictureInPicture())}{config.fullscreen && controlButton(state.fullscreen ? "Exit fullscreen" : "Fullscreen", state.fullscreen ? "compress" : "fullscreen", () => void (state.fullscreen ? exitFullscreen() : requestFullscreen()))}</div></div>;
  return <div ref={containerRef} className={`media-player media-player-${type} ${className}`} style={{ "--media-primary": accent } as React.CSSProperties} tabIndex={0} onKeyDown={onKeyDown} onDoubleClick={(event) => { if (type !== "video" || (event.target as HTMLElement).closest("button,input,.media-menu,.volume-popover,.media-controls")) return; const bounds = event.currentTarget.getBoundingClientRect(); const position = event.clientX - bounds.left; if (position < bounds.width * .35) showSeekFeedback("back"); else if (position > bounds.width * .65) showSeekFeedback("forward"); }}>
    {type === "video" ? <video {...mediaProps} ref={mediaRef as React.RefObject<HTMLVideoElement>}>{captions.map((track) => <track key={track.src} {...track} kind={track.kind ?? "subtitles"} />)}{chapters && <track {...chapters} kind="chapters" />}</video> : <div className="audio-stage"><div className="audio-artwork">{artwork ? <img src={artwork} alt="" /> : <Icon name="music" size={38} />}</div><div className="audio-copy">{mediaSession?.title && <strong>{mediaSession.title}</strong>}{mediaSession?.artist && <span>{mediaSession.artist}</span>}</div><div className="audio-wave" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /></div><audio {...mediaProps} ref={mediaRef as React.RefObject<HTMLAudioElement>}>{captions.map((track) => <track key={track.src} {...track} kind={track.kind ?? "subtitles"} />)}</audio></div>}
    {utilityControls}
    {type === "video" && !state.playing && !state.error && controlButton("Play", "play", () => void togglePlay(), false, "center-play")}
    {seekFeedback && <div className={`seek-feedback ${seekFeedback}`}><Icon name={seekFeedback === "back" ? "skip-back" : "skip-forward"} size={24} /><span>{seekStep}s</span></div>}
    {state.buffering && <div className="media-loading" role="status"><span /> Loading</div>}{state.error && <div className="media-error" role="alert"><strong>Playback unavailable</strong><span>{state.error.message}</span><button type="button" onClick={() => { setState((current) => ({ ...current, error: undefined })); mediaRef.current?.load(); }}>Retry</button></div>}{notice && <div className="media-notice" role="status">{notice}</div>}{controlsMarkup}{settingsPanel}
  </div>;
});